---
- hosts: all
  become: yes
  name: play01
  tasks:
    - name: Basically "apt update"
      apt: 
        update_cache=yes

    - name: INSTALL LEMP packages 
      apt: name={{ item }} state=latest
      with_items:
           - nginx
           - mysql-client
           - mysql-server
           - python3-mysqldb
           - php-fpm
           - php-mysql
    
    - name: START services
      service: name={{ item }} state=started enabled=true
      with_items:
           - nginx
           - mysql

# Nginx Configuration
    - name: Sets Nginx conf file
      template:
        src: "files/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/ngnix.conf"

    - name: Enables new site
      file:
        src: "/etc/nginx/sites-available/ngnix.conf"
        dest: "/etc/nginx/sites-enabled/ngnix.conf"
        state: link
      notify: Reload Nginx
    
    - name: Removes "default" site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: Reload Nginx


# Sets Up PHP Info Page
    - name: Sets Up PHP Info Page
      template:
        src: "files/info.php.j2"
        dest: "/var/www/html/info.php"

# Copy source code   
    - name: copy html file
      copy: src=index.php dest=/var/www/html/index.php mode=0664


# MySQL Configuration

    - name: Setup MYSQL root password
      mysql_user: name=root host=localhost password=8V2@db

    - name: Create DB user
      mysql_user: login_user=root login_password=8V2@db user=dbadmin password=8V2@apk priv=*.*:ALL state=present
  
    - name: Create DATABASE
      mysql_db: login_user=root login_password=8V2@db db=kelltondb state=present


# Set Up Phpmyadmin
    - name: INSTALL LEMP packages
      apt: name={{ item }} state=latest
      with_items:
           - php
           - php-gd
           - php-cli
           - php-common
           - unzip
           - phpmyadmin    

# Set Up Phpmyadmin link
    - name: create symbolic link /usr/share/phpmyadmin -> /var/www/html/phpmyadmin
      file:
        src: /usr/share/phpmyadmin
        dest: /var/www/html/phpmyadmin
        state: link
    
  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

    - name: Restart Nginx
      service:
        name: nginx
        state: restarted
